# Generated by Django 5.1.1 on 2024-10-04 07:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(default=uuid.uuid4, max_length=64, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("site_url", models.URLField(blank=True, null=True, unique=True)),
                ("validity_duration", models.PositiveIntegerField(default=86400)),
                ("auto_set_expiration", models.BooleanField(default=True)),
            ],
        ),
    ]
