# Generated by Django 5.1.1 on 2024-10-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("keygen", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
